#!/bin/bash

# Automates full training process (hyperparameter selection, training and validation).

set -e

here=$(dirname "$0")
name=$(basename "$0")

if [[ $# -ne 1 ]]; then
    cat >&2 <<EOF
Usage: $0 <model>

Train model <model> in three stages: hyperparameter selection, training and validation.
EOF
    exit 1
fi

model_name="$1"

. "${here}/tools/common"

mkdir -p "${log_dir}"

# Stage 1: Hyperparameter selection. grid_dir contains .json files which contain hyperparameters to tune.
"${here}/autotune" "${model_name}"

# Stage 1.5: Process results in the background.
"${here}/tools/prep-results" "${model_name}" &

# Stage 2: Training.
"${here}/train" "${model_name}"
log_dest="${log_dir}/training.log"
cp "${log_path}" "${log_dest}"

# Stage 3: Validation.
"${python}" "${here}/src/validator.py" "${model_name}"
log_dest="${log_dir}/validation.log"
cp "${log_path}" "${log_dest}"
