#!/bin/bash

# Run hyperparameter selection.

set -e

here=$(dirname "$0")
name=$(basename "$0")
model_name="$1"

data_dir="${here}/data"
model_dir="${data_dir}/${model_name}"
log_dir="${model_dir}/logs"
log_path="${data_dir}/mldisasm.log"
grid_dir="${model_dir}/grids"
config_path="${model_dir}/config.json"
config_bak="${config_path}~"

mkdir -p "${grid_dir}"

for grid in ${grid_dir}/*; do
    if [[ ! -x "${grid}" ]]; then
        echo "$0: Skipping non-executable file ${grid}" >&2
        continue
    fi
    # Back up the previous config.
    cp   "${config_path}" "${config_bak}"
    # Append the grid to the config file.
    tmp_path=$(mktemp)
    cat  "${config_path}" | head -n -1 >"${tmp_path}"
    mv   "${tmp_path}" "${config_path}"
    echo -e ",\n\"grid\":" >>"${config_path}"
    cat  "${grid}" >>"${config_path}"
    echo "}" >>"${config_path}"
    # Select parameters from the grid.
    "${here}/tune" "${model_name}"
    # Copy the log file.
    log_name=$(basename "${grid%.json}")
    log_dest="${log_dir}/${log_name}.log"
    cp "${log_path}" "${log_dest}"
    # If everything succeeded, remove the executable flag from the grid so we skip it next time.
    chmod -x "${grid}"
done
