#!/bin/bash

# Automates full training process (hyperparameter selection, training and validation).

set -e

here=$(dirname "$0")
name=$(basename "$0")

if [[ $# -ne 1 ]]; then
    cat >&2 <<EOF
Usage: $0 <model>

Train model <model> in three stages: hyperparameter selection, training and validation.
EOF
    exit 1
fi

model_name="$1"

data_dir="${here}/data"
log_path="${data_dir}/mldisasm.log"
model_dir="${data_dir}/${model_name}"
log_dir="${model_dir}/logs"

python=$(which python3)

mkdir -p "${log_dir}"

[[ "x${MLD_PYTHON}" != "x" ]] && python="${MLD_PYTHON}"

if [[ ! -x $(which "${python}") ]]; then
    echo "$0: Python \"${python}\" is not an executable file in the \$PATH" >&2
    exit 1
fi

# Stage 1: Hyperparameter selection. grid_dir contains .json files which contain hyperparameters to tune.
"${here}/autotune" "${model_name}"

# Stage 2: Training.
"${here}/train" "${model_name}"
log_dest="${log_dir}/training.log"
cp "${log_path}" "${log_dest}"

# Stage 3: Validation.
"${python}" "${here}/src/validator.py" "${model_name}"
log_dest="${log_dir}/validation.log"
cp "${log_path}" "${log_dest}"
