#!/bin/bash

here=$(dirname "$0")

[[ "x${MLD_PYTHON}" = "x" ]] && MLD_PYTHON="python3"
[[ "${MLD_TRACE}" = "1" ]] && PYTHON_ARGS=("-m trace -l")

time "${MLD_PYTHON}" ${PYTHON_ARGS} "${here}/src/tuner.py" $*
