#!/usr/bin/env python3

'''
Filter ndisasm output.
'''

from   signal import signal, SIGPIPE, SIG_DFL
import sys

if __name__ == '__main__':
    # Ignore closed pipe error.
    signal(SIGPIPE, SIG_DFL)
    for line in sys.stdin:
        # Break on space and ignore the first column, which contains the offset.
        elems = line.split()
        # Element 1 contains the bytes, remaining columns are the disassembly.
        print('{}|{}'.format(
            elems[1],
            ' '.join(elems[2:])
        ))
